apiVersion: v1
kind: Secret
metadata:
    name: my-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:UuvA7A+kczG1p5AW6hsF2ZMJ3w==,iv:/l7GLAEuLpnip0ARMM2ABw8FPAYOk0fBU0nFp7IIeKE=,tag:VWVauTn3buzuaix22dT+lw==,type:str]
sops:
    age:
        - recipient: age1ykvvtd35yar24tvm59znqczxfwfw770d4e43aagqu7r3mwtmvavqjtqqc7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXa1c1L0cvWWJpQXdQdUI0
            S0JqKzlqZXBLM210dXh5Ukxsc29UbWRDMmcwCmtzYVhNSTJxbk1TTzNMV1hORWYz
            cVAwUmxRZjNxVGJFYVBKSGZSUXVEYTgKLS0tIGwwYWlkZVZ4ZUlMdFAxaEo2eWNX
            NXVHK2hCVlVrZGh5T1dmZTVwYXYwRHMK4pf4+jXADvNOULxRQbfDfg3eJYS9+P6l
            F/F5ewzx7Y4rm0qH5E70wgFLkaPKnbrF7LNT+TZxQUuiPgs7QDVpEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T15:31:46Z"
    mac: ENC[AES256_GCM,data:U9VUZFy1NURBwHojH4Q2HyRmT/KOkdx56JuSP+xzhEIHveiaSRKsL6pH/g2hJ7sMNdbm4S1unFpSXs+Q18OeGrCPrY/iHtiAr6tpT+Ov4qnxO284/cHweUIlGJutytg8zadN8cOdniaANfepoiw9tsdAkbm21OXL0oq4iDMiuxU=,iv:eOJiHWJubGX4rWoZaf0uW6hstYzf3a7zbmhbxsVcSEo=,tag:8IU7HoSkblOwZ8Xj++Moqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
